```java
package trywithresources;

import java.io.IOException;

public class Device implements AutoCloseable {
    String header = null;
    public void open() {
        header = "OPENED";
        System.out.println("Device Opened");
    }

    public String read() throws IOException {
        throw new IOException("Unknown");
    }

    public void writeHeader(String str) throws IOException {
        System.out.println("Writing : " + str);
        header = str;
    }

    public void close() {
        System.out.println("Device closed");
        header = null;
    }

    public static void testDevice() {
        Device d = new Device();
        try {
            d.open();
            d.read();
            d.writeHeader("TEST");
            d.close();
        } catch(IOException ex) {
            System.out.println("Got Exception");
        }
    }

    public static void main(String[] args) {
        Device.testDevice();
    }
}
```
Ответ:
```
Device Opened
Got Exception
```